### ISSUE TITLE
On a failure, kafka-configurator stops dead instead of logging and continuing with other topics.

### ISSUE THREAD

**Issue by oliverlockwood** [sky-uk/kafka-configurator#18]
Logs look like this:

```
Running kafka-configurator 0.5.0 with args: -f=/etc/topic-configuration.yml, --zookeeper=...
Replication factor unchanged for topic-a.
No change in number of partitions for topic-a
No change in config for topic-a
Replication factor unchanged for topic-b.
No change in number of partitions for topic-b
No change in config for topic-b
Replication factor unchanged for topic-c.
No change in number of partitions for topic-c
No change in config for topic-c
Failed to configure topic-d
com.sky.kafka.configurator.error.package$ReplicationChangeFound$: Changing replication factor is unsupported
	at com.sky.kafka.configurator.error.package$ReplicationChangeFound$.<clinit>(package.scala)
	at com.sky.kafka.configurator.TopicConfigurator.failReplicationChange(TopicConfigurator.scala:42)
	at com.sky.kafka.configurator.TopicConfigurator.$anonfun$updateTopic$1(TopicConfigurator.scala:35)
	at com.sky.kafka.configurator.TopicConfigurator.ifDifferent$1(TopicConfigurator.scala:30)
	at com.sky.kafka.configurator.TopicConfigurator.updateTopic(TopicConfigurator.scala:35)
	at com.sky.kafka.configurator.TopicConfigurator.configure(TopicConfigurator.scala:16)
	at com.sky.kafka.configurator.Main$.$anonfun$configureTopicsFromFile$2(Main.scala:54)
	at cats.Traverse.$anonfun$traverseU$1(Traverse.scala:51)
	at cats.instances.ListInstances$$anon$1.$anonfun$traverse$2(list.scala:70)
	at cats.instances.ListInstances$$anon$1.loop$2(list.scala:58)
	at cats.instances.ListInstances$$anon$1.$anonfun$foldRight$1(list.scala:58)
	at cats.Eval$Compute.loop$1(Eval.scala:279)
	at cats.Eval$Compute.value(Eval.scala:293)
	at cats.Eval$Call.value(Eval.scala:229)
	at cats.instances.ListInstances$$anon$1.traverse(list.scala:69)
	at cats.instances.ListInstances$$anon$1.traverse(list.scala:12)
	at cats.Applicative.traverse(Applicative.scala:35)
	at cats.Applicative.traverse$(Applicative.scala:16)
	at cats.instances.TryInstances$$anon$1.traverse(try.scala:14)
	at cats.Traverse.traverseU(Traverse.scala:51)
	at cats.Traverse.traverseU$(Traverse.scala:16)
	at cats.instances.ListInstances$$anon$1.traverseU(list.scala:12)
	at cats.Traverse$Ops.traverseU(Traverse.scala:16)
	at cats.Traverse$Ops.traverseU$(Traverse.scala:16)
	at cats.Traverse$ToTraverseOps$$anon$4.traverseU(Traverse.scala:16)
	at com.sky.kafka.configurator.Main$.$anonfun$configureTopicsFromFile$1(Main.scala:53)
	at scala.util.Success.flatMap(Try.scala:247)
	at com.sky.kafka.configurator.Main$.configureTopicsFromFile(Main.scala:52)
	at com.sky.kafka.configurator.Main$.$anonfun$run$1(Main.scala:44)
	at scala.util.Success.flatMap(Try.scala:247)
	at com.sky.kafka.configurator.Main$.run(Main.scala:42)
	at com.sky.kafka.configurator.Main$.main(Main.scala:33)
	at com.sky.kafka.configurator.Main.main(Main.scala)
```

Consequently, it does not attempt to configure Topics e, f, g etc.

Which is not the intended behaviour.

**Comment by oliverlockwood** [comment]
Fix released in version `0.6.0`
